import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Analytics from "@/components/Analytics";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cramora AI – The Fastest Way to Prep for Exams",
  description:
    "Cramora AI converts messy notes into 1-page cram sheets, predicts test questions, and helps you study faster.",
  applicationName: "Cramora AI",
  icons: {
    icon: "/CramoraAI.png",
    shortcut: "/CramoraAI.png",
    apple: "/CramoraAI.png",
  },
  openGraph: {
    title: "Cramora AI – The Fastest Way to Prep for Exams",
    description:
      "AI-powered cram sheets, predicted test questions, and active recall practice.",
    url: "https://cramora.com",
    siteName: "Cramora AI",
    images: [
      {
        url: "/og_banner.png", // optional OG preview image
        width: 1200,
        height: 630,
        alt: "Cramora AI – Study Faster",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Cramora AI – The Fastest Way to Prep for Exams",
    description:
      "Your AI-powered study tool for cram sheets, predictions, and active recall.",
  },
};

// export const metadata: Metadata = {
//   title: "Cramora AI",
//   description: "Generated by Cramora",
//   icons: {
//     icon: "/CramoraAI_Logo.png",
//     shortcut: "/CramoraAI_Logo.png",
//     apple: "/CramoraAI_Logo.png",
//   },
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />

      </body>
    </html>
  );
}
